### ISSUE TITLE
Add commenting and/or automated rubric

### ISSUE THREAD

**Issue by egregius313** [ThePyrotechnic/pygrader#5]
The grader can currently upload the grades to Canvas, but currently it would be useful to allow it to either update a rubric, or add submission comments.

So if we have the following entry in failures.json: 
```json
{
   "John Doe": {
      "if-then": -2,
      "nand": -1
   }
}
```
Where John Doe has the id 48879, a comment would be uploaded
> Failed if-then: -2
   Failed nand: -1
    - Ed Minnix on January 31 at 10:32

**Comment by ThePyrotechnic** [comment]
Should add a `"comment"` parameter to test case; if it is defined then, when posting the comments, use that instead of the test name.
failures.json would look more like:
```json
{
   "John Doe": {
      "if-then": {
         "loss": -2,
         "comment": "Failed if-then"
      },
      "nand": {
         "loss": -1,
         "comment": "nand didn't work properly"
      }
   }
}
```
... or more concisely (but maybe with less readable code):
```json
{
   "John Doe": {
      "if-then": [-2, "Failed if-then"],
      "nand": [-1, "nand didn't work properly"]
   }
}
```
